POST http://127.0.0.1:8000/api/noticias_modificar/
Authorization: Token 7939d2aefc22439bbf16da778c2c2628
Content-Type: application/json

{
    "id": 2,
    "titulo": "Contenido del nuevo título de la noticia",
    "contenido": "Nuevo contenido de la noticia"

}
